In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras.optimizers import Adam, SGD, RMSprop
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import xgboost as xgb
from catboost import CatBoostRegressor
from sklearn.multioutput import MultiOutputRegressor
from catboost import CatBoostRegressor
import lightgbm as lgb
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

%matplotlib inline

2025-09-16 18:15:40.307493: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1758046540.334000   12010 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1758046540.341895   12010 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [2]:
df1=pd.read_excel("/kaggle/input/rainfall-prediction-challenge-2025/Data Aktual.xlsx")
df2=pd.read_excel("/kaggle/input/rainfall-prediction-challenge-2025/Data Input Hybrid.xlsx")

In [3]:
df1.head()

        Date  Aktual_Y1  Aktual_Y2  Aktual_Y3  Aktual_Y4
0 2013-01-01      57.83      62.25      66.28      66.28
1 2013-01-02      47.53      53.67      57.54      57.54
2 2013-01-03       5.33       7.20       7.92       7.92
3 2013-01-04      12.54       8.85       6.92       6.92
4 2013-01-05       7.43       6.84       8.08       8.08

In [4]:
df1.shape

(4017, 5)

In [5]:
df1.isnull().sum()

Date         0
Aktual_Y1    0
Aktual_Y2    0
Aktual_Y3    0
Aktual_Y4    0
dtype: int64

In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4017 entries, 0 to 4016
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       4017 non-null   datetime64[ns]
 1   Aktual_Y1  4017 non-null   float64
 2   Aktual_Y2  4017 non-null   float64
 3   Aktual_Y3  4017 non-null   float64
 4   Aktual_Y4  4017 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 157.0 KB

In [7]:
df2.head()

,Tanggal,w1,w2,w3,w4,ehat1,eresid1,ehat2,eresid2,ehat3,eresid3,ehat4,eresid4
0,2013-01-05,-0.536191,-5.487963,-3.669789,-4.130197,2.018349,-26.844071,-0.516930,-4.264845,-0.229540,-2.374609,-0.022629,-1.343081
1,2013-01-06,-3.327927,-7.747863,-7.029111,-7.321747,2.200193,-5.469971,-0.246884,8.296666,-0.367963,3.662227,-0.040259,3.613250
2,2013-01-07,5.528366,1.756227,4.811639,3.619966,0.934243,-20.512956,-0.703296,-5.540482,0.149313,-4.300833,0.026537,-3.561647
3,2013-01-08,-4.972129,-7.771838,-7.604647,-7.611148,1.481614,-22.569946,-0.089907,-3.900944,-0.307566,-4.152582,-0.046692,-3.072028
4,2013-01-09,-3.951102,-8.223785,-6.535069,-7.321102,1.747543,-20.661473,-0.380272,-1.043197,-0.203747,-2.759564,-0.044268,-2.269412

In [8]:
df2.shape

(4013, 13)

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4013 entries, 0 to 4012
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tanggal  4013 non-null   datetime64[ns]
 1   w1       4013 non-null   float64
 2   w2       4013 non-null   float64
 3   w3       4013 non-null   float64
 4   w4       4013 non-null   float64
 5   ehat1    4013 non-null   float64
 6   eresid1  4013 non-null   float64
 7   ehat2    4013 non-null   float64
 8   eresid2  4013 non-null   float64
 9   ehat3    4013 non-null   float64
 10  eresid3  4013 non-null   float64
 11  ehat4    4013 non-null   float64
 12  eresid4  4013 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 407.7 KB

In [10]:
df2.head()

,Tanggal,w1,w2,w3,w4,ehat1,eresid1,ehat2,eresid2,ehat3,eresid3,ehat4,eresid4
0,2013-01-05,-0.536191,-5.487963,-3.669789,-4.130197,2.018349,-26.844071,-0.516930,-4.264845,-0.229540,-2.374609,-0.022629,-1.343081
1,2013-01-06,-3.327927,-7.747863,-7.029111,-7.321747,2.200193,-5.469971,-0.246884,8.296666,-0.367963,3.662227,-0.040259,3.613250
2,2013-01-07,5.528366,1.756227,4.811639,3.619966,0.934243,-20.512956,-0.703296,-5.540482,0.149313,-4.300833,0.026537,-3.561647
3,2013-01-08,-4.972129,-7.771838,-7.604647,-7.611148,1.481614,-22.569946,-0.089907,-3.900944,-0.307566,-4.152582,-0.046692,-3.072028
4,2013-01-09,-3.951102,-8.223785,-6.535069,-7.321102,1.747543,-20.661473,-0.380272,-1.043197,-0.203747,-2.759564,-0.044268,-2.269412

In [11]:
df2['Tanggal'] = pd.to_datetime(df2['Tanggal'], format='%d-%b-%Y')
df2['Day'] = df2['Tanggal'].dt.day
df2['Month'] = df2['Tanggal'].dt.month
df2['Year'] = df2['Tanggal'].dt.year

In [12]:
df2.drop(columns=["Tanggal"],axis=1,inplace=True)

In [13]:
df2.head()

,w1,w2,w3,w4,ehat1,eresid1,ehat2,eresid2,ehat3,eresid3,ehat4,eresid4,Day,Month,Year
0,-0.536191,-5.487963,-3.669789,-4.130197,2.018349,-26.844071,-0.516930,-4.264845,-0.229540,-2.374609,-0.022629,-1.343081,5,1,2013
1,-3.327927,-7.747863,-7.029111,-7.321747,2.200193,-5.469971,-0.246884,8.296666,-0.367963,3.662227,-0.040259,3.613250,6,1,2013
2,5.528366,1.756227,4.811639,3.619966,0.934243,-20.512956,-0.703296,-5.540482,0.149313,-4.300833,0.026537,-3.561647,7,1,2013
3,-4.972129,-7.771838,-7.604647,-7.611148,1.481614,-22.569946,-0.089907,-3.900944,-0.307566,-4.152582,-0.046692,-3.072028,8,1,2013
4,-3.951102,-8.223785,-6.535069,-7.321102,1.747543,-20.661473,-0.380272,-1.043197,-0.203747,-2.759564,-0.044268,-2.269412,9,1,2013

In [14]:
input_cols = ['w1', 'w2', 'w3', 'w4', 'ehat1', 'ehat2', 'ehat3', 'ehat4']
target_cols = ['eresid1', 'eresid2', 'eresid3', 'eresid4']

scaler=MinMaxScaler()
df2[input_cols]=scaler.fit_transform(df2[input_cols])

In [15]:
df2.head()

,w1,w2,w3,w4,ehat1,eresid1,ehat2,eresid2,ehat3,eresid3,ehat4,eresid4,Day,Month,Year
0,0.155260,0.111268,0.140664,0.127793,0.837998,-26.844071,0.589346,-4.264845,0.225970,-2.374609,0.129884,-1.343081,5,1,2013
1,0.132941,0.095580,0.118107,0.105804,0.850875,-5.469971,0.668414,8.296666,0.193665,3.662227,0.112061,3.613250,6,1,2013
2,0.203744,0.161554,0.197615,0.181188,0.761234,-20.512956,0.534779,-5.540482,0.314384,-4.300833,0.179590,-3.561647,7,1,2013
3,0.119797,0.095414,0.114242,0.103811,0.799993,-22.569946,0.714376,-3.900944,0.207760,-4.152582,0.105557,-3.072028,8,1,2013
4,0.127959,0.092277,0.121424,0.105809,0.818823,-20.661473,0.629359,-1.043197,0.231989,-2.759564,0.108008,-2.269412,9,1,2013

In [16]:
X = df2[input_cols]
y = df2[target_cols]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True,random_state=42)

In [18]:
base_model = CatBoostRegressor(iterations=1000,learning_rate=0.005,depth=6,verbose=500)

multi_model = MultiOutputRegressor(base_model)  

multi_model.fit(X_train, y_train)

0:	learn: 8.5513541	total: 48.4ms	remaining: 48.4s
500:	learn: 7.9076158	total: 800ms	remaining: 797ms
999:	learn: 7.5770018	total: 1.63s	remaining: 0us
0:	learn: 6.7946891	total: 1.76ms	remaining: 1.76s
500:	learn: 6.3985141	total: 758ms	remaining: 755ms
999:	learn: 6.1986917	total: 1.51s	remaining: 0us
0:	learn: 6.5448734	total: 2.27ms	remaining: 2.27s
500:	learn: 6.1845656	total: 759ms	remaining: 756ms
999:	learn: 5.9997718	total: 1.51s	remaining: 0us
0:	learn: 6.4714262	total: 2.28ms	remaining: 2.27s
500:	learn: 6.1055870	total: 755ms	remaining: 752ms
999:	learn: 5.9222452	total: 1.5s	remaining: 0us

MultiOutputRegressor(estimator=<catboost.core.CatBoostRegressor object at 0x7b76fb98a710>)

In [19]:
y_true_all = y_test[target_cols].values.flatten()
y_pred = multi_model.predict(X_test)

y_pred_all = y_pred.flatten()

rmse_all = np.sqrt(mean_squared_error(y_true_all, y_pred_all))
mae_all = mean_absolute_error(y_true_all, y_pred_all)
r2_all = r2_score(y_true_all, y_pred_all)
mape_all = (np.abs(y_true_all - y_pred_all) / np.maximum(y_true_all, 1e-6)).mean() * 100


print(f"RMSE : {rmse_all:.4f}")
print(f"MAE  : {mae_all:.4f}")
print(f"R2   : {r2_all:.4f}")
print(f"MAPE : {mape_all:.2f}%")

RMSE : 6.5999
MAE  : 3.9334
R2   : 0.0417
MAPE : 188714313.08%

In [20]:
# Convert DataFrame to NumPy array before reshaping
X_train_np = X_train.values
X_test_np  = X_test.values

# Reshape for LSTM: (samples, timesteps, features)
# Here timesteps = 1
X_train_3d = X_train_np.reshape((X_train_np.shape[0], 1, X_train_np.shape[1]))
X_test_3d  = X_test_np.reshape((X_test_np.shape[0], 1, X_test_np.shape[1]))

print(f"X_train shape: {X_train_3d.shape}")
print(f"X_test shape:  {X_test_3d.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape:  {y_test.shape}")

X_train shape: (3210, 1, 8)
X_test shape:  (803, 1, 8)
y_train shape: (3210, 4)
y_test shape:  (803, 4)

In [21]:
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, BatchNormalization
from keras.optimizers import Adam

n_features = X_train_3d.shape[2]
n_outputs  = y_train.shape[1]

model = Sequential([
    LSTM(128, activation='tanh', return_sequences=True, input_shape=(X_train_3d.shape[1], n_features)),
    Dropout(0.2),
    BatchNormalization(),
    
    LSTM(64, activation='tanh'),
    Dropout(0.2),
    
    Dense(32, activation='relu'),
    Dense(n_outputs)  
])


optimizer = Adam(learning_rate=5e-5)
model.compile(optimizer=optimizer,loss='mean_squared_error',metrics=['mean_squared_error'])

model.summary()

2025-09-16 18:15:53.189776: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/usr/local/lib/python3.11/dist-packages/keras/src/layers/rnn/rnn.py:200: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 1, 128)         │        70,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1, 128)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 1, 128)         │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           132 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 122,276 (477.64 KB)

 Trainable params: 122,020 (476.64 KB)

 Non-trainable params: 256 (1.00 KB)

In [22]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)

reduce_lr = ReduceLROnPlateau(monitor='val_loss',factor=0.5,patience=10,min_lr=1e-6,verbose=1)

In [23]:
history = model.fit(X_train_3d, y_train,epochs=150,batch_size=64,validation_data=(X_test_3d, y_test),verbose=2, callbacks=[early_stop, reduce_lr])

Epoch 1/150
51/51 - 7s - 129ms/step - loss: 51.0325 - mean_squared_error: 51.0325 - val_loss: 45.4561 - val_mean_squared_error: 45.4561 - learning_rate: 5.0000e-05
Epoch 2/150
51/51 - 0s - 6ms/step - loss: 51.0334 - mean_squared_error: 51.0334 - val_loss: 45.4559 - val_mean_squared_error: 45.4559 - learning_rate: 5.0000e-05
Epoch 3/150
51/51 - 0s - 6ms/step - loss: 51.0353 - mean_squared_error: 51.0353 - val_loss: 45.4558 - val_mean_squared_error: 45.4558 - learning_rate: 5.0000e-05
Epoch 4/150
51/51 - 0s - 6ms/step - loss: 51.0248 - mean_squared_error: 51.0248 - val_loss: 45.4554 - val_mean_squared_error: 45.4554 - learning_rate: 5.0000e-05
Epoch 5/150
51/51 - 0s - 6ms/step - loss: 51.0305 - mean_squared_error: 51.0305 - val_loss: 45.4551 - val_mean_squared_error: 45.4551 - learning_rate: 5.0000e-05
Epoch 6/150
51/51 - 0s - 6ms/step - loss: 51.0338 - mean_squared_error: 51.0338 - val_loss: 45.4542 - val_mean_squared_error: 45.4542 - learning_rate: 5.0000e-05
Epoch 7/150
51/51 - 0s - 6ms/step - loss: 51.0183 - mean_squared_error: 51.0183 - val_loss: 45.4536 - val_mean_squared_error: 45.4536 - learning_rate: 5.0000e-05
Epoch 8/150
51/51 - 0s - 6ms/step - loss: 51.0342 - mean_squared_error: 51.0342 - val_loss: 45.4522 - val_mean_squared_error: 45.4522 - learning_rate: 5.0000e-05
Epoch 9/150
51/51 - 0s - 6ms/step - loss: 51.0187 - mean_squared_error: 51.0187 - val_loss: 45.4507 - val_mean_squared_error: 45.4507 - learning_rate: 5.0000e-05
Epoch 10/150
51/51 - 0s - 6ms/step - loss: 51.0319 - mean_squared_error: 51.0319 - val_loss: 45.4486 - val_mean_squared_error: 45.4486 - learning_rate: 5.0000e-05
Epoch 11/150
51/51 - 0s - 6ms/step - loss: 51.0240 - mean_squared_error: 51.0240 - val_loss: 45.4461 - val_mean_squared_error: 45.4461 - learning_rate: 5.0000e-05
Epoch 12/150
51/51 - 0s - 6ms/step - loss: 51.0103 - mean_squared_error: 51.0103 - val_loss: 45.4431 - val_mean_squared_error: 45.4431 - learning_rate: 5.0000e-05
Epoch 13/150
51/51 - 0s - 6ms/step - loss: 51.0239 - mean_squared_error: 51.0239 - val_loss: 45.4397 - val_mean_squared_error: 45.4397 - learning_rate: 5.0000e-05
Epoch 14/150
51/51 - 0s - 6ms/step - loss: 51.0164 - mean_squared_error: 51.0164 - val_loss: 45.4355 - val_mean_squared_error: 45.4355 - learning_rate: 5.0000e-05
Epoch 15/150
51/51 - 0s - 6ms/step - loss: 51.0084 - mean_squared_error: 51.0084 - val_loss: 45.4318 - val_mean_squared_error: 45.4318 - learning_rate: 5.0000e-05
Epoch 16/150
51/51 - 0s - 7ms/step - loss: 51.0136 - mean_squared_error: 51.0136 - val_loss: 45.4283 - val_mean_squared_error: 45.4283 - learning_rate: 5.0000e-05
Epoch 17/150
51/51 - 0s - 7ms/step - loss: 51.0044 - mean_squared_error: 51.0044 - val_loss: 45.4242 - val_mean_squared_error: 45.4242 - learning_rate: 5.0000e-05
Epoch 18/150
51/51 - 0s - 7ms/step - loss: 51.0128 - mean_squared_error: 51.0128 - val_loss: 45.4221 - val_mean_squared_error: 45.4221 - learning_rate: 5.0000e-05
Epoch 19/150
51/51 - 0s - 6ms/step - loss: 50.9964 - mean_squared_error: 50.9964 - val_loss: 45.4198 - val_mean_squared_error: 45.4198 - learning_rate: 5.0000e-05
Epoch 20/150
51/51 - 0s - 6ms/step - loss: 51.0009 - mean_squared_error: 51.0009 - val_loss: 45.4149 - val_mean_squared_error: 45.4149 - learning_rate: 5.0000e-05
Epoch 21/150
51/51 - 0s - 6ms/step - loss: 50.9931 - mean_squared_error: 50.9931 - val_loss: 45.4094 - val_mean_squared_error: 45.4094 - learning_rate: 5.0000e-05
Epoch 22/150
51/51 - 0s - 6ms/step - loss: 51.0000 - mean_squared_error: 51.0000 - val_loss: 45.4053 - val_mean_squared_error: 45.4053 - learning_rate: 5.0000e-05
Epoch 23/150
51/51 - 0s - 7ms/step - loss: 50.9939 - mean_squared_error: 50.9939 - val_loss: 45.4001 - val_mean_squared_error: 45.4001 - learning_rate: 5.0000e-05
Epoch 24/150
51/51 - 0s - 6ms/step - loss: 50.9809 - mean_squared_error: 50.9809 - val_loss: 45.3972 - val_mean_squared_error: 45.3972 - learning_rate: 5.0000e-05
Epoch 25/150
51/51 - 0s - 6ms/step - loss: 50.9792 - mean_squared_error: 50.9792 - val_loss: 45.3907 - val_mean_squared_error: 45.3907 - learning_rate: 5.0000e-05
Epoch 26/150
51/51 - 0s - 7ms/step - loss: 50.9792 - mean_squared_error: 50.9792 - val_loss: 45.3877 - val_mean_squared_error: 45.3877 - learning_rate: 5.0000e-05
Epoch 27/150
51/51 - 0s - 6ms/step - loss: 50.9697 - mean_squared_error: 50.9697 - val_loss: 45.3817 - val_mean_squared_error: 45.3817 - learning_rate: 5.0000e-05
Epoch 28/150
51/51 - 0s - 6ms/step - loss: 50.9728 - mean_squared_error: 50.9728 - val_loss: 45.3756 - val_mean_squared_error: 45.3756 - learning_rate: 5.0000e-05
Epoch 29/150
51/51 - 0s - 6ms/step - loss: 50.9532 - mean_squared_error: 50.9532 - val_loss: 45.3689 - val_mean_squared_error: 45.3689 - learning_rate: 5.0000e-05
Epoch 30/150
51/51 - 0s - 6ms/step - loss: 50.9540 - mean_squared_error: 50.9540 - val_loss: 45.3618 - val_mean_squared_error: 45.3618 - learning_rate: 5.0000e-05
Epoch 31/150
51/51 - 0s - 6ms/step - loss: 50.9559 - mean_squared_error: 50.9559 - val_loss: 45.3549 - val_mean_squared_error: 45.3549 - learning_rate: 5.0000e-05
Epoch 32/150
51/51 - 0s - 6ms/step - loss: 50.9380 - mean_squared_error: 50.9380 - val_loss: 45.3485 - val_mean_squared_error: 45.3485 - learning_rate: 5.0000e-05
Epoch 33/150
51/51 - 0s - 6ms/step - loss: 50.9351 - mean_squared_error: 50.9351 - val_loss: 45.3414 - val_mean_squared_error: 45.3414 - learning_rate: 5.0000e-05
Epoch 34/150
51/51 - 0s - 6ms/step - loss: 50.9186 - mean_squared_error: 50.9186 - val_loss: 45.3315 - val_mean_squared_error: 45.3315 - learning_rate: 5.0000e-05
Epoch 35/150
51/51 - 0s - 7ms/step - loss: 50.9194 - mean_squared_error: 50.9194 - val_loss: 45.3231 - val_mean_squared_error: 45.3231 - learning_rate: 5.0000e-05
Epoch 36/150
51/51 - 0s - 7ms/step - loss: 50.9153 - mean_squared_error: 50.9153 - val_loss: 45.3148 - val_mean_squared_error: 45.3148 - learning_rate: 5.0000e-05
Epoch 37/150
51/51 - 0s - 6ms/step - loss: 50.8932 - mean_squared_error: 50.8932 - val_loss: 45.2996 - val_mean_squared_error: 45.2996 - learning_rate: 5.0000e-05
Epoch 38/150
51/51 - 0s - 6ms/step - loss: 50.8936 - mean_squared_error: 50.8936 - val_loss: 45.2878 - val_mean_squared_error: 45.2878 - learning_rate: 5.0000e-05
Epoch 39/150
51/51 - 0s - 6ms/step - loss: 50.8766 - mean_squared_error: 50.8766 - val_loss: 45.2785 - val_mean_squared_error: 45.2785 - learning_rate: 5.0000e-05
Epoch 40/150
51/51 - 0s - 6ms/step - loss: 50.8597 - mean_squared_error: 50.8597 - val_loss: 45.2664 - val_mean_squared_error: 45.2664 - learning_rate: 5.0000e-05
Epoch 41/150
51/51 - 0s - 7ms/step - loss: 50.8640 - mean_squared_error: 50.8640 - val_loss: 45.2554 - val_mean_squared_error: 45.2554 - learning_rate: 5.0000e-05
Epoch 42/150
51/51 - 0s - 7ms/step - loss: 50.8386 - mean_squared_error: 50.8386 - val_loss: 45.2424 - val_mean_squared_error: 45.2424 - learning_rate: 5.0000e-05
Epoch 43/150
51/51 - 0s - 6ms/step - loss: 50.8375 - mean_squared_error: 50.8375 - val_loss: 45.2258 - val_mean_squared_error: 45.2258 - learning_rate: 5.0000e-05
Epoch 44/150
51/51 - 0s - 6ms/step - loss: 50.8042 - mean_squared_error: 50.8042 - val_loss: 45.2129 - val_mean_squared_error: 45.2129 - learning_rate: 5.0000e-05
Epoch 45/150
51/51 - 0s - 7ms/step - loss: 50.8012 - mean_squared_error: 50.8012 - val_loss: 45.1959 - val_mean_squared_error: 45.1959 - learning_rate: 5.0000e-05
Epoch 46/150
51/51 - 0s - 6ms/step - loss: 50.8036 - mean_squared_error: 50.8036 - val_loss: 45.1801 - val_mean_squared_error: 45.1801 - learning_rate: 5.0000e-05
Epoch 47/150
51/51 - 0s - 6ms/step - loss: 50.7583 - mean_squared_error: 50.7583 - val_loss: 45.1620 - val_mean_squared_error: 45.1620 - learning_rate: 5.0000e-05
Epoch 48/150
51/51 - 0s - 6ms/step - loss: 50.7545 - mean_squared_error: 50.7545 - val_loss: 45.1445 - val_mean_squared_error: 45.1445 - learning_rate: 5.0000e-05
Epoch 49/150
51/51 - 0s - 6ms/step - loss: 50.7196 - mean_squared_error: 50.7196 - val_loss: 45.1216 - val_mean_squared_error: 45.1216 - learning_rate: 5.0000e-05
Epoch 50/150
51/51 - 0s - 6ms/step - loss: 50.7238 - mean_squared_error: 50.7238 - val_loss: 45.1046 - val_mean_squared_error: 45.1046 - learning_rate: 5.0000e-05
Epoch 51/150
51/51 - 0s - 6ms/step - loss: 50.7048 - mean_squared_error: 50.7048 - val_loss: 45.0860 - val_mean_squared_error: 45.0860 - learning_rate: 5.0000e-05
Epoch 52/150
51/51 - 0s - 6ms/step - loss: 50.6904 - mean_squared_error: 50.6904 - val_loss: 45.0675 - val_mean_squared_error: 45.0675 - learning_rate: 5.0000e-05
Epoch 53/150
51/51 - 0s - 6ms/step - loss: 50.6487 - mean_squared_error: 50.6487 - val_loss: 45.0412 - val_mean_squared_error: 45.0412 - learning_rate: 5.0000e-05
Epoch 54/150
51/51 - 0s - 6ms/step - loss: 50.6710 - mean_squared_error: 50.6710 - val_loss: 45.0211 - val_mean_squared_error: 45.0211 - learning_rate: 5.0000e-05
Epoch 55/150
51/51 - 0s - 6ms/step - loss: 50.6208 - mean_squared_error: 50.6208 - val_loss: 45.0000 - val_mean_squared_error: 45.0000 - learning_rate: 5.0000e-05
Epoch 56/150
51/51 - 0s - 7ms/step - loss: 50.5875 - mean_squared_error: 50.5875 - val_loss: 44.9800 - val_mean_squared_error: 44.9800 - learning_rate: 5.0000e-05
Epoch 57/150
51/51 - 0s - 6ms/step - loss: 50.5858 - mean_squared_error: 50.5858 - val_loss: 44.9624 - val_mean_squared_error: 44.9624 - learning_rate: 5.0000e-05
Epoch 58/150
51/51 - 0s - 6ms/step - loss: 50.5587 - mean_squared_error: 50.5587 - val_loss: 44.9362 - val_mean_squared_error: 44.9362 - learning_rate: 5.0000e-05
Epoch 59/150
51/51 - 0s - 6ms/step - loss: 50.5532 - mean_squared_error: 50.5532 - val_loss: 44.9144 - val_mean_squared_error: 44.9144 - learning_rate: 5.0000e-05
Epoch 60/150
51/51 - 0s - 6ms/step - loss: 50.5042 - mean_squared_error: 50.5042 - val_loss: 44.8880 - val_mean_squared_error: 44.8880 - learning_rate: 5.0000e-05
Epoch 61/150
51/51 - 0s - 6ms/step - loss: 50.4544 - mean_squared_error: 50.4544 - val_loss: 44.8632 - val_mean_squared_error: 44.8632 - learning_rate: 5.0000e-05
Epoch 62/150
51/51 - 0s - 6ms/step - loss: 50.4740 - mean_squared_error: 50.4740 - val_loss: 44.8365 - val_mean_squared_error: 44.8365 - learning_rate: 5.0000e-05
Epoch 63/150
51/51 - 0s - 7ms/step - loss: 50.4383 - mean_squared_error: 50.4383 - val_loss: 44.8149 - val_mean_squared_error: 44.8149 - learning_rate: 5.0000e-05
Epoch 64/150
51/51 - 0s - 6ms/step - loss: 50.4067 - mean_squared_error: 50.4067 - val_loss: 44.7989 - val_mean_squared_error: 44.7989 - learning_rate: 5.0000e-05
Epoch 65/150
51/51 - 0s - 6ms/step - loss: 50.3846 - mean_squared_error: 50.3846 - val_loss: 44.7701 - val_mean_squared_error: 44.7701 - learning_rate: 5.0000e-05
Epoch 66/150
51/51 - 0s - 6ms/step - loss: 50.3660 - mean_squared_error: 50.3660 - val_loss: 44.7455 - val_mean_squared_error: 44.7455 - learning_rate: 5.0000e-05
Epoch 67/150
51/51 - 0s - 6ms/step - loss: 50.4031 - mean_squared_error: 50.4031 - val_loss: 44.7251 - val_mean_squared_error: 44.7251 - learning_rate: 5.0000e-05
Epoch 68/150
51/51 - 0s - 6ms/step - loss: 50.3571 - mean_squared_error: 50.3571 - val_loss: 44.7070 - val_mean_squared_error: 44.7070 - learning_rate: 5.0000e-05
Epoch 69/150
51/51 - 0s - 6ms/step - loss: 50.3154 - mean_squared_error: 50.3154 - val_loss: 44.6798 - val_mean_squared_error: 44.6798 - learning_rate: 5.0000e-05
Epoch 70/150
51/51 - 0s - 6ms/step - loss: 50.2762 - mean_squared_error: 50.2762 - val_loss: 44.6483 - val_mean_squared_error: 44.6483 - learning_rate: 5.0000e-05
Epoch 71/150
51/51 - 0s - 6ms/step - loss: 50.2754 - mean_squared_error: 50.2754 - val_loss: 44.6303 - val_mean_squared_error: 44.6303 - learning_rate: 5.0000e-05
Epoch 72/150
51/51 - 0s - 6ms/step - loss: 50.2356 - mean_squared_error: 50.2356 - val_loss: 44.6064 - val_mean_squared_error: 44.6064 - learning_rate: 5.0000e-05
Epoch 73/150
51/51 - 0s - 6ms/step - loss: 50.2524 - mean_squared_error: 50.2524 - val_loss: 44.5794 - val_mean_squared_error: 44.5794 - learning_rate: 5.0000e-05
Epoch 74/150
51/51 - 0s - 6ms/step - loss: 50.2127 - mean_squared_error: 50.2127 - val_loss: 44.5625 - val_mean_squared_error: 44.5625 - learning_rate: 5.0000e-05
Epoch 75/150
51/51 - 0s - 7ms/step - loss: 50.1304 - mean_squared_error: 50.1304 - val_loss: 44.5377 - val_mean_squared_error: 44.5377 - learning_rate: 5.0000e-05
Epoch 76/150
51/51 - 0s - 6ms/step - loss: 50.1663 - mean_squared_error: 50.1663 - val_loss: 44.5169 - val_mean_squared_error: 44.5169 - learning_rate: 5.0000e-05
Epoch 77/150
51/51 - 0s - 6ms/step - loss: 50.1629 - mean_squared_error: 50.1629 - val_loss: 44.4920 - val_mean_squared_error: 44.4920 - learning_rate: 5.0000e-05
Epoch 78/150
51/51 - 0s - 6ms/step - loss: 50.0712 - mean_squared_error: 50.0712 - val_loss: 44.4666 - val_mean_squared_error: 44.4666 - learning_rate: 5.0000e-05
Epoch 79/150
51/51 - 0s - 6ms/step - loss: 50.1387 - mean_squared_error: 50.1387 - val_loss: 44.4499 - val_mean_squared_error: 44.4499 - learning_rate: 5.0000e-05
Epoch 80/150
51/51 - 0s - 6ms/step - loss: 50.0645 - mean_squared_error: 50.0645 - val_loss: 44.4228 - val_mean_squared_error: 44.4228 - learning_rate: 5.0000e-05
Epoch 81/150
51/51 - 0s - 6ms/step - loss: 50.1030 - mean_squared_error: 50.1030 - val_loss: 44.3991 - val_mean_squared_error: 44.3991 - learning_rate: 5.0000e-05
Epoch 82/150
51/51 - 0s - 6ms/step - loss: 49.9820 - mean_squared_error: 49.9820 - val_loss: 44.3865 - val_mean_squared_error: 44.3865 - learning_rate: 5.0000e-05
Epoch 83/150
51/51 - 0s - 6ms/step - loss: 49.9969 - mean_squared_error: 49.9969 - val_loss: 44.3674 - val_mean_squared_error: 44.3674 - learning_rate: 5.0000e-05
Epoch 84/150
51/51 - 0s - 6ms/step - loss: 49.9923 - mean_squared_error: 49.9923 - val_loss: 44.3476 - val_mean_squared_error: 44.3476 - learning_rate: 5.0000e-05
Epoch 85/150
51/51 - 0s - 6ms/step - loss: 49.8509 - mean_squared_error: 49.8509 - val_loss: 44.3362 - val_mean_squared_error: 44.3362 - learning_rate: 5.0000e-05
Epoch 86/150
51/51 - 0s - 6ms/step - loss: 49.9416 - mean_squared_error: 49.9416 - val_loss: 44.3224 - val_mean_squared_error: 44.3224 - learning_rate: 5.0000e-05
Epoch 87/150
51/51 - 0s - 7ms/step - loss: 49.8837 - mean_squared_error: 49.8837 - val_loss: 44.2929 - val_mean_squared_error: 44.2929 - learning_rate: 5.0000e-05
Epoch 88/150
51/51 - 0s - 6ms/step - loss: 49.9513 - mean_squared_error: 49.9513 - val_loss: 44.2730 - val_mean_squared_error: 44.2730 - learning_rate: 5.0000e-05
Epoch 89/150
51/51 - 0s - 6ms/step - loss: 49.9018 - mean_squared_error: 49.9018 - val_loss: 44.2622 - val_mean_squared_error: 44.2622 - learning_rate: 5.0000e-05
Epoch 90/150
51/51 - 0s - 7ms/step - loss: 49.8615 - mean_squared_error: 49.8615 - val_loss: 44.2415 - val_mean_squared_error: 44.2415 - learning_rate: 5.0000e-05
Epoch 91/150
51/51 - 0s - 7ms/step - loss: 49.9100 - mean_squared_error: 49.9100 - val_loss: 44.2186 - val_mean_squared_error: 44.2186 - learning_rate: 5.0000e-05
Epoch 92/150
51/51 - 0s - 6ms/step - loss: 49.8062 - mean_squared_error: 49.8062 - val_loss: 44.2097 - val_mean_squared_error: 44.2097 - learning_rate: 5.0000e-05
Epoch 93/150
51/51 - 0s - 7ms/step - loss: 49.8296 - mean_squared_error: 49.8296 - val_loss: 44.1924 - val_mean_squared_error: 44.1924 - learning_rate: 5.0000e-05
Epoch 94/150
51/51 - 0s - 7ms/step - loss: 49.8035 - mean_squared_error: 49.8035 - val_loss: 44.1672 - val_mean_squared_error: 44.1672 - learning_rate: 5.0000e-05
Epoch 95/150
51/51 - 0s - 7ms/step - loss: 49.7612 - mean_squared_error: 49.7612 - val_loss: 44.1589 - val_mean_squared_error: 44.1589 - learning_rate: 5.0000e-05
Epoch 96/150
51/51 - 0s - 7ms/step - loss: 49.7663 - mean_squared_error: 49.7663 - val_loss: 44.1385 - val_mean_squared_error: 44.1385 - learning_rate: 5.0000e-05
Epoch 97/150
51/51 - 0s - 6ms/step - loss: 49.7632 - mean_squared_error: 49.7632 - val_loss: 44.1181 - val_mean_squared_error: 44.1181 - learning_rate: 5.0000e-05
Epoch 98/150
51/51 - 0s - 6ms/step - loss: 49.6959 - mean_squared_error: 49.6959 - val_loss: 44.1074 - val_mean_squared_error: 44.1074 - learning_rate: 5.0000e-05
Epoch 99/150
51/51 - 0s - 6ms/step - loss: 49.6686 - mean_squared_error: 49.6686 - val_loss: 44.0910 - val_mean_squared_error: 44.0910 - learning_rate: 5.0000e-05
Epoch 100/150
51/51 - 0s - 6ms/step - loss: 49.8150 - mean_squared_error: 49.8150 - val_loss: 44.0857 - val_mean_squared_error: 44.0857 - learning_rate: 5.0000e-05
Epoch 101/150
51/51 - 0s - 6ms/step - loss: 49.7406 - mean_squared_error: 49.7406 - val_loss: 44.0746 - val_mean_squared_error: 44.0746 - learning_rate: 5.0000e-05
Epoch 102/150
51/51 - 0s - 6ms/step - loss: 49.7297 - mean_squared_error: 49.7297 - val_loss: 44.0568 - val_mean_squared_error: 44.0568 - learning_rate: 5.0000e-05
Epoch 103/150
51/51 - 0s - 6ms/step - loss: 49.4840 - mean_squared_error: 49.4840 - val_loss: 44.0315 - val_mean_squared_error: 44.0315 - learning_rate: 5.0000e-05
Epoch 104/150
51/51 - 0s - 6ms/step - loss: 49.5100 - mean_squared_error: 49.5100 - val_loss: 44.0220 - val_mean_squared_error: 44.0220 - learning_rate: 5.0000e-05
Epoch 105/150
51/51 - 0s - 6ms/step - loss: 49.4262 - mean_squared_error: 49.4262 - val_loss: 44.0002 - val_mean_squared_error: 44.0002 - learning_rate: 5.0000e-05
Epoch 106/150
51/51 - 0s - 6ms/step - loss: 49.6303 - mean_squared_error: 49.6303 - val_loss: 44.0015 - val_mean_squared_error: 44.0015 - learning_rate: 5.0000e-05
Epoch 107/150
51/51 - 0s - 6ms/step - loss: 49.6371 - mean_squared_error: 49.6371 - val_loss: 43.9934 - val_mean_squared_error: 43.9934 - learning_rate: 5.0000e-05
Epoch 108/150
51/51 - 0s - 6ms/step - loss: 49.6428 - mean_squared_error: 49.6428 - val_loss: 43.9775 - val_mean_squared_error: 43.9775 - learning_rate: 5.0000e-05
Epoch 109/150
51/51 - 0s - 6ms/step - loss: 49.4811 - mean_squared_error: 49.4811 - val_loss: 43.9656 - val_mean_squared_error: 43.9656 - learning_rate: 5.0000e-05
Epoch 110/150
51/51 - 0s - 6ms/step - loss: 49.7234 - mean_squared_error: 49.7234 - val_loss: 43.9576 - val_mean_squared_error: 43.9576 - learning_rate: 5.0000e-05
Epoch 111/150
51/51 - 0s - 6ms/step - loss: 49.5328 - mean_squared_error: 49.5328 - val_loss: 43.9459 - val_mean_squared_error: 43.9459 - learning_rate: 5.0000e-05
Epoch 112/150
51/51 - 0s - 7ms/step - loss: 49.4066 - mean_squared_error: 49.4066 - val_loss: 43.9271 - val_mean_squared_error: 43.9271 - learning_rate: 5.0000e-05
Epoch 113/150
51/51 - 0s - 6ms/step - loss: 49.6261 - mean_squared_error: 49.6261 - val_loss: 43.9298 - val_mean_squared_error: 43.9298 - learning_rate: 5.0000e-05
Epoch 114/150
51/51 - 0s - 6ms/step - loss: 49.6894 - mean_squared_error: 49.6894 - val_loss: 43.9194 - val_mean_squared_error: 43.9194 - learning_rate: 5.0000e-05
Epoch 115/150
51/51 - 0s - 6ms/step - loss: 49.5316 - mean_squared_error: 49.5316 - val_loss: 43.9087 - val_mean_squared_error: 43.9087 - learning_rate: 5.0000e-05
Epoch 116/150
51/51 - 0s - 6ms/step - loss: 49.6167 - mean_squared_error: 49.6167 - val_loss: 43.9065 - val_mean_squared_error: 43.9065 - learning_rate: 5.0000e-05
Epoch 117/150
51/51 - 0s - 7ms/step - loss: 49.5518 - mean_squared_error: 49.5518 - val_loss: 43.9087 - val_mean_squared_error: 43.9087 - learning_rate: 5.0000e-05
Epoch 118/150
51/51 - 0s - 6ms/step - loss: 49.5403 - mean_squared_error: 49.5403 - val_loss: 43.9029 - val_mean_squared_error: 43.9029 - learning_rate: 5.0000e-05
Epoch 119/150
51/51 - 0s - 6ms/step - loss: 49.5597 - mean_squared_error: 49.5597 - val_loss: 43.8957 - val_mean_squared_error: 43.8957 - learning_rate: 5.0000e-05
Epoch 120/150
51/51 - 0s - 7ms/step - loss: 49.4955 - mean_squared_error: 49.4955 - val_loss: 43.8789 - val_mean_squared_error: 43.8789 - learning_rate: 5.0000e-05
Epoch 121/150
51/51 - 0s - 6ms/step - loss: 49.4450 - mean_squared_error: 49.4450 - val_loss: 43.8801 - val_mean_squared_error: 43.8801 - learning_rate: 5.0000e-05
Epoch 122/150
51/51 - 0s - 7ms/step - loss: 49.4095 - mean_squared_error: 49.4095 - val_loss: 43.8748 - val_mean_squared_error: 43.8748 - learning_rate: 5.0000e-05
Epoch 123/150

In [24]:
y_pred = model.predict(X_test_3d)
rmse_overall = np.sqrt(mean_squared_error(y_test, y_pred))
mae_overall  = mean_absolute_error(y_test, y_pred)
r2_overall   = r2_score(y_test, y_pred)
mape_overall = np.mean(np.abs((y_test - y_pred) / y_test)) * 100

print("Overall Metrics:")
print(f"RMSE : {rmse_overall:.4f}")
print(f"MAE  : {mae_overall:.4f}")
print(f"R2   : {r2_overall:.4f}")
print(f"MAPE : {mape_overall:.2f}%")

26/26 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step
Overall Metrics:
RMSE : 6.6161
MAE  : 3.9160
R2   : 0.0357
MAPE : 297.07%

In [41]:
X_submission = df2[input_cols].iloc[-100:].values
X_submission_3d = X_submission.reshape((X_submission.shape[0], 1, X_submission.shape[1]))

y_pred_submission = model.predict(X_submission_3d)

submission_df = pd.DataFrame({
    'id': range(len(y_pred_submission)),
    'Y1': y_pred_submission[:, 0],
    'Y2': y_pred_submission[:, 1],
    'Y3': y_pred_submission[:, 2],
    'Y4': y_pred_submission[:, 3]
})

submission_df.to_csv("lstm_submission.csv", index=False)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

In [42]:
df=pd.read_csv("/kaggle/working/lstm_submission.csv")

In [43]:
df.head()

   id        Y1        Y2        Y3        Y4
0   0  1.112891  1.197157  1.063259  1.058061
1   1  0.709734  0.658697  0.626224  0.689312
2   2  0.909269  0.928712  0.849294  0.868365
3   3  0.952969  0.976678  0.884238  0.903448
4   4  1.122937  1.206078  1.067503  1.065986